# This is a basic workflow to help you get started with Actions

name: Merge branch Develop and Feature

on:
  push:
    branches:
      - "feature/*"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'develop'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
