# This is a basic workflow to help you get started with Actions

name: 'Up merge'

on:
  push:
    branches: [ feature/first ]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: echo message
        run: |
          echo "echo hello"
