# File: .github/workflows/pull-request.yml

on:
  push:
    branches:
    - 'main'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
        echo "hello world"
