# This is a basic workflow to help you get started with Actions

name: 'Up merge'

on:
  push:
    branches:
      - 'feature/*'

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Up Merge
      uses: bambamboole/gha-upmerge@master
      with:
        stable_branch: 'develop'
        development_branch: 'feature/*'
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
